name: validate

on:
  push:
    branches:
    - pipeline
    paths-ignore:
    - '**/README.md'
jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        run: |
          echo "$HOME/.bin" >> $GITHUB_PATH
          curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh > /tmp/tfswitch-install.sh
          chmod +x /tmp/tfswitch-install.sh
          /tmp/tfswitch-install.sh -b $HOME/.bin
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: get terraform
        run: |
          export TF_VERSION=1.0.5
          tfswitch -b $HOME/.bin/terraform
      -
        name: terraform init 
        run: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && echo "$m - init" && terraform init -input=false -backend=true) || exit 1; done
      -
        name: terraform validate
        run: find . -name ".terraform" -prune -o -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (cd "$m" && echo "$m - validate" && terraform validate && echo "√ $m") || exit 1 ; done
      -
        name: terraform new vpc check
        run: |
          export project_name="test-$CI_COMMIT_SHORT_SHA"
          terraform plan -var="ibmcloud_api_key=${{ secrets.IBMCLOUD_API_KEY }}" -var="region=eu-gb" -var="ssh_key=hyperion-eu-gb" -var="resource_group=CDE"  -var="project_name=$project_name" -out default.tfplan